default_language_version:
    python: python3.12

default_stages: [ pre-commit, pre-push ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v6.0.0
        hooks:
            -   id: check-toml
            -   id: check-yaml
            -   id: check-json
            -   id: debug-statements
            -   id: trailing-whitespace
            -   id: check-added-large-files
            -   id: check-merge-conflict
            -   id: fix-byte-order-marker
            -   id: name-tests-test
                args: [ --pytest-test-first ]
            -   id: end-of-file-fixer
                exclude: LICENSE
            -   id: no-commit-to-branch
