default_language_version:
    python: python3.9

default_stages: [ commit, push ]

repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
            -   id: check-toml
            -   id: check-yaml
            -   id: check-json
            -   id: debug-statements
            -   id: trailing-whitespace
            -   id: check-added-large-files
            -   id: check-merge-conflict
            -   id: fix-byte-order-marker
            -   id: name-tests-test
                args: [ --pytest-test-first ]
                exclude: images/
            -   id: end-of-file-fixer
                exclude: LICENSE

    -   repo: local
        hooks:
            -   id: ruff
                name: ruff
                entry: ruff check
                types: [ python ]
                language: system

    -   repo: local
        hooks:
            -   id: black
                name: black
                entry: black --config pyproject.toml
                types: [ python ]
                language: system
