version: "3"

env:
    CONDA: micromamba

vars:
    PROJECT: safecheck
    TESTS: tests

tasks:
    env-create:
        cmd: $CONDA env create -n {{.PROJECT}} --file env.yml --yes

    env-remove:
        cmd: $CONDA env remove -n {{.PROJECT}} --yes

    uv-add-dev:
        cmd: |
            uv add --dev pytest pytest-html hypothesis coverage pytest-cov pytest-benchmark coverage-badge ruff pre-commit black pyright[nodejs] typing-extensions bandit numpy torch jax notebook line-profiler

    pre-commit-install:
        cmd: uv run pre-commit install

    pre-commit-all:
        cmd: uv run pre-commit run --all-files

    format:
        cmds:
            - uv run ruff check {{.PROJECT}} --fix
            - uv run black --config pyproject.toml {{.PROJECT}} {{.TESTS}}

    test:
        cmds:
            - uv run pytest -rsx -c pyproject.toml --cov={{.PROJECT}} {{.TESTS}}/
            - uv run genbadge coverage -i coverage.xml -o assets/coverage.svg

    lint:
        cmds:
            - uv run ruff check {{.PROJECT}}
            - uv run black --diff --check --config pyproject.toml {{.PROJECT}} {{.TESTS}}

    typing:
        cmd: uv run pyright

    typing-quality:
        cmd: uv run pyright --ignoreexternal --verifytypes {{.PROJECT}}

    safety:
        cmd: uv run bandit -ll --recursive {{.PROJECT}} {{.TESTS}}

    check:
        cmds:
            - task: lint
            - task: typing
            - task: test
            - task: safety

    build:
        cmd: uv build

    publish:
        cmd: uv publish --skip-existing

    sysinfo:
        cmd: uv run python .github/system_info.py
