name: 🐛 Bug report
description: Report an issue
title: "🐛 <Please write a comprehensive title and keep the 🐛 prefix>"
labels: [ bug ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear description the bug. If you want to contribute to fix this issue, tell us in the description.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction
      description: A [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) is **required**, otherwise the issue might be closed without further notice.
      placeholder: Reproduction
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: System Info
      description: Output of `task sysinfo`
      render: Shell
      placeholder: Paste the output of the following command
    validations:
      required: true
  - type: checkboxes
    id: validations
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guide](https://github.com/davnn/safecheck/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't already an issue that reports the same bug to avoid creating duplicates.
          required: true
