name: 📝 Documentation improvement
description: Something is erroneous, unclear or missing in the docs.
title: "📝 <Please write a comprehensive title and keep the 📝 prefix>"
labels: [ documentation ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to help us improve the documentation!
  - type: textarea
    id: documentation-description
    attributes:
      label: Description
      description: 'Explain how you would like to improve the docs here!'
    validations:
      required: true
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: Before submitting the issue, please make sure you do the following
      options:
        - label: Read the [Contributing Guide](https://github.com/davnn/safecheck/blob/main/.github/CONTRIBUTING.md).
          required: true
        - label: Check that there isn't already an issue requesting the same.
          required: true
