name: Release

on:
    release:
        types: [ published ]
    workflow_dispatch:

jobs:
    build:
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest ]
                python: [ "3.12" ]
        uses: ./.github/workflows/setup.yml
        secrets: inherit
        with:
            os: ${{ matrix.os }}
            python: ${{ matrix.python }}
            command: task build && task publish
