name: Setup

on:
    workflow_call:
        inputs:
            python:
                required: true
                type: string
            os:
                required: true
                type: string
            command:
                required: true
                type: string

env:
    UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}

jobs:
    setup:
        runs-on: ${{ inputs.os }}
        steps:
            - uses: actions/checkout@v4

            - name: Install Task
              uses: arduino/setup-task@v1
              with:
                  version: 3.x
                  repo-token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install uv
              run: |
                  curl -LsSf https://astral.sh/uv/install.sh | sh
                  echo "${HOME}/.local/bin" >> $GITHUB_PATH

            - name: Set up Python ${{ inputs.python }}
              uses: actions/setup-python@v5
              with:
                  python-version: ${{ inputs.python }}
                  cache: "pip" # uv reuses pip’s cache structure

            - name: Install dependencies with uv
              run: uv sync

            - name: Command
              run: ${{ inputs.command }}
              shell: bash
